before_install:
  - sudo apt-get update
  - sudo apt install -qy texlive-full latexmk

script:
  - make

branches:
  except:
    - master

deploy:
  provider: releases
  api_key: $TOKEN
  file_glob: true
  file: dist/$TRAVIS_TAG--*.pdf
  skip_cleanup: true
  on:
    tags: true
