before_install:
  - sudo apt-get update
  - sudo apt install -qy texlive-full latexmk

script:
  - make

deploy:
  provider: releases
  api_key: $TOKEN
  file_glob: true
  file: */$TRAVIS_TAG*.pdf
  skip_cleanup: true
  on:
    tags: true
